language: c

env:
  matrix:
    - PYTHON_VERSION=2.7 UNITPKG=false
    - PYTHON_VERSION=3.3 UNITPKG=false
    - PYTHON_VERSION=3.4 UNITPKG=false
    - PYTHON_VERSION=2.7 UNITPKG=true
    - PYTHON_VERSION=3.3 UNITPKG=true
    - PYTHON_VERSION=3.4 UNITPKG=true

before_install:
    - source .continuous-integration/travis/setup_environment_$TRAVIS_OS_NAME.sh
    - conda create --yes -n test python=$PYTHON_VERSION
    - source activate test

install:
    - conda install --yes pip pytest numpy
    - pip install coveralls pytest-cov traitlets
    - if [[ $UNITPKG == true ]]; then conda install --yes astropy; fi
    - if [[ $UNITPKG == true ]]; then pip install quantities pint; fi
    - if [[ $PYTHON_VERSION == 2.6 ]]; then conda install --yes unittest2; fi

script:
    - py.test --cov numtraits.py

after_success:
  - coveralls
